ARG BASE
ARG MAINTAINER

FROM ${BASE} as base
LABEL maintainer = $MAINTAINER


RUN apt update

RUN apt install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa

RUN apt update
RUN apt upgrade


RUN apt-get install -y tesseract-ocr
RUN apt-get install -y tesseract-ocr-eng
RUN apt-get install -y poppler-utils

RUN apt install --no-install-recommends -y \
	apache2 \
	build-essential \
	libapache2-mod-wsgi-py3 \
	python3 \
	python3-pip \
	python3-setuptools

RUN apt clean -y
RUN apt autoremove -y

RUN rm -rf /var/lib/apt/lists/*
RUN pip3 install --upgrade pip